2025-07-05 15:29:55 | INFO | logger_config.py:39 | 日志系统已初始化，日志文件: API\log\20250705\152955.log
2025-07-05 15:29:55 | INFO | service.py:35 | 模型位置: D:\00deeplearn\yolo11\【2】训练模型\cls\train_new\weights\best.pt
2025-07-05 15:29:55 | INFO | service.py:200 | 服务启动在端口: 5000
2025-07-05 15:30:08 | INFO | service.py:80 | 接收到请求 - 雪橇号码: 1378, 日期: 20250521
2025-07-05 15:30:08 | INFO | service.py:84 | 接收到图片数据
2025-07-05 15:30:11 | INFO | service.py:108 | .....................
2025-07-05 15:30:11 | DEBUG | service.py:109 | 模型所有类别: {0: 'C', 1: 'M', 2: 'S'}
2025-07-05 15:30:11 | INFO | service.py:110 | 检测类别结果: M
2025-07-05 15:30:11 | INFO | service.py:111 | ----------------------
2025-07-05 15:30:11 | INFO | service.py:147 | 图像处理完成，准备显示结果
2025-07-05 15:30:14 | ERROR | db_utils.py:33 | 数据库连接失败: 'dict' object has no attribute 'host'
2025-07-05 15:30:14 | INFO | service.py:64 | 创建响应 - 状态码: 200, 消息: detection_success, 检测类别: M
2025-07-05 15:32:57 | INFO | service.py:80 | 接收到请求 - 雪橇号码: 1378, 日期: 20250521
2025-07-05 15:32:57 | INFO | service.py:84 | 接收到图片数据
2025-07-05 15:32:57 | INFO | service.py:108 | .....................
2025-07-05 15:32:57 | DEBUG | service.py:109 | 模型所有类别: {0: 'C', 1: 'M', 2: 'S'}
2025-07-05 15:32:57 | INFO | service.py:110 | 检测类别结果: M
2025-07-05 15:32:57 | INFO | service.py:111 | ----------------------
2025-07-05 15:32:57 | INFO | service.py:147 | 图像处理完成，准备显示结果
2025-07-05 15:33:00 | ERROR | db_utils.py:33 | 数据库连接失败: 'dict' object has no attribute 'host'
2025-07-05 15:33:00 | INFO | service.py:64 | 创建响应 - 状态码: 200, 消息: detection_success, 检测类别: M
2025-07-05 15:33:36 | INFO | service.py:80 | 接收到请求 - 雪橇号码: 1378, 日期: 20250521
2025-07-05 15:33:36 | INFO | service.py:84 | 接收到图片数据
2025-07-05 15:33:36 | INFO | service.py:108 | .....................
2025-07-05 15:33:36 | DEBUG | service.py:109 | 模型所有类别: {0: 'C', 1: 'M', 2: 'S'}
2025-07-05 15:33:36 | INFO | service.py:110 | 检测类别结果: M
2025-07-05 15:33:36 | INFO | service.py:111 | ----------------------
2025-07-05 15:33:36 | INFO | service.py:147 | 图像处理完成，准备显示结果
2025-07-05 15:33:40 | ERROR | db_utils.py:33 | 数据库连接失败: 'dict' object has no attribute 'host'
2025-07-05 15:33:40 | INFO | service.py:64 | 创建响应 - 状态码: 200, 消息: detection_success, 检测类别: M
2025-07-05 15:34:26 | INFO | service.py:80 | 接收到请求 - 雪橇号码: 1378, 日期: 20250521
2025-07-05 15:34:26 | INFO | service.py:84 | 接收到图片数据
2025-07-05 15:34:26 | INFO | service.py:108 | .....................
2025-07-05 15:34:26 | DEBUG | service.py:109 | 模型所有类别: {0: 'C', 1: 'M', 2: 'S'}
2025-07-05 15:34:26 | INFO | service.py:110 | 检测类别结果: M
2025-07-05 15:34:26 | INFO | service.py:111 | ----------------------
2025-07-05 15:34:26 | INFO | service.py:147 | 图像处理完成，准备显示结果
2025-07-05 15:34:31 | ERROR | db_utils.py:33 | 数据库连接失败: 'dict' object has no attribute 'host'
2025-07-05 15:34:31 | INFO | service.py:64 | 创建响应 - 状态码: 200, 消息: detection_success, 检测类别: M
